name: 'DeployInfraWebapp'
description: 'Deploys Infrastructure and WebApp'

inputs:
  azureClientId:
    description: 'Azure App Registration Client ID'
    required: true

  azureSubscriptionId:
    description: 'Azure Subscription ID'
    required: true

  azureTenantId:
    description: 'Azure Tenant ID'
    required: true

  deploymentSlotName:
    description: 'Name of the deployment slot.  If not specified, uses Production.'
    required: false
    default: Production

  environmentId:
    description: 'Short name for the environment being deployed to'
    required: true

  location:
    description: 'Azure location where the subscription will record logs for deployments'
    required: true

  package:
    description: 'Path to the build package'
    required: false
    default: ./build

  parametersFile:
    description: 'Path to the ARM parameters file'
    required: false
    default: './infra/main.parameters.json'

  templateFile:
    description: 'Path to the ARM template (JSON or Bicep)'
    required: false
    default: './infra/main.bicep'

outputs:
  resourceGroupName:
    description: 'Name of the Azure Resource Group that contains the WebApp'
    value: ${{ steps.deployStep.outputs.resourceGroupName }}
    
  webAppName:
    description: 'Name of the Azure WebApp that the application is deployed to'
    value: ${{ steps.deployStep.outputs.webAppName }}

runs:
  using: composite
  steps:
    # Download Artifacts
    - name: 'Download Artifacts'
      uses: actions/download-artifact@v3
      continue-on-error: false
        
    # Log in to Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ inputs.azureClientId }}
        tenant-id: ${{ inputs.azureTenantId }}
        subscription-id: ${{ inputs.azureSubscriptionId }}

    # Deploy resources to Azure
    - uses: azure/arm-deploy@v1
      id: deployStep
      with:
        scope: subscription
        subscriptionId: ${{ inputs.azureSubscriptionId }}
        region: ${{ inputs.location }}
        template: ${{ inputs.templateFile }}
        parameters: ${{ inputs.parametersFile }}

    # Deploy code to web app
    - name: 'Deploy code to the WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.deployStep.outputs.webAppName }}
        slot-name: ${{ inputs.deploymentSlotName }}
        package: ${{ inputs.package }}

    - name: 'Deployment Message'
      run: echo "Deployed Application to ${{ inputs.environmentId }}"
      shell: bash

    - name: 'Create Summary Log Message'
      run: |
        echo '# DeployInfraWebApp' >> $GITHUB_STEP_SUMMARY
        echo '## :rocket: ${{ inputs.environmentId }}' >> $GITHUB_STEP_SUMMARY
        echo 'Infrastructure deployed to Azure:' >> $GITHUB_STEP_SUMMARY
        echo '- Subscription ID: **${{ inputs.azureSubscriptionId }}**' >> $GITHUB_STEP_SUMMARY
        echo '- Resource Group: **${{ steps.deployStep.outputs.resourceGroupName }}**' >> $GITHUB_STEP_SUMMARY
        echo 'Application deployed to Azure WebApp: **${{ steps.deployStep.outputs.webAppName }}**' >> $GITHUB_STEP_SUMMARY
      shell: bash
